apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: monitoring
  labels:
    app: thanos-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      containers:
        - name: thanos-query
          image: quay.io/thanos/thanos:v0.30.0
          args:
            - 'query'
            - '--log.level=debug'
            - '--query.replica-label=prometheus_replica'
            - '--store=XX.XX.XX.XX:30901' # cluster-a
            - '--store=XX.XX.XX.XX:30901' # cluster-n
            - '--store=prometheus-stack-kube-prom-thanos-external.monitoring.svc.cluster.local:10901' # ops-cluster
            - '--store=thanos-store-svc.monitoring.svc.cluster.local:10901' # store svc          
          resources:
            requests:
              cpu: '100m'
              memory: '64Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
          ports:
            - name: http
              containerPort: 10902
            - name: grpc
              containerPort: 10901
            - name: cluster
              containerPort: 10900
